Feature/tasks
abolychev/dualboot-taskmanager pull request #15
Opened 2022-10-25 17:56 UTC by abolychev

2022-11-07 06:28 UTC, greybutton requested changes

2022-11-07 06:28 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'id desc'
давай сортировку через рансак делать, и не хардкодить на бэке

2022-11-07 06:28 UTC, greybutton commented on app/javascript/components/AddPopup/index.js
> +import AddPopup from './AddPopup.js';
точно надо `.js';` в индекс файлах?

2022-11-07 06:28 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +function EditPopup({ cardId, onClose, onDestroyCard, onLoadCard, onUpdateCard }) {
почему поменял паттерн onEntityAction => onActionEntity?

2022-11-07 06:28 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from 'components/EditPopup';
перемешаны импорты

2022-11-07 06:28 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  const [openedTaskId, setOpenedTaskId] = useState(null);
лучше все useState где то вверху обозначить

2022-11-07 06:28 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +      handleClose();
комменты убрать

2022-11-07 06:28 UTC, greybutton commented on package.json
> +    "ramda": "^0.28.0",
не хватае qs

2022-11-07 12:56 UTC, abolychev commented on app/javascript/components/AddPopup/index.js
> +import AddPopup from './AddPopup.js';
Да точно, всегда так было. А почему нет?

2022-11-07 12:59 UTC, abolychev commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'id desc'
"поправить сортировку на бэкенде, чтобы новые карточки появлялись вверху колонки." - я это так понял. search.sorts - это механизм рансак. А как по другому?

2022-11-07 13:07 UTC, abolychev commented on app/javascript/components/EditPopup/EditPopup.js
> +function EditPopup({ cardId, onClose, onDestroyCard, onLoadCard, onUpdateCard }) {
Честно паттерна не заметил. Были ошибки в именовании обработчиков, поправил их приведя к одному виду.

2022-11-07 13:16 UTC, abolychev commented on app/javascript/components/EditPopup/EditPopup.js
> +function EditPopup({ cardId, onClose, onDestroyCard, onLoadCard, onUpdateCard }) {
А разве он был? Вот из предыдущего задания - onCreateCard.
Переделать все на onEntityAction?

2022-11-07 13:50 UTC, abolychev commented on package.json
> +    "ramda": "^0.28.0",
Не понял :(

2022-11-09 08:24 UTC, greybutton requested changes

2022-11-09 08:24 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'id desc'
через дефолт рансак параметра, чтобы был дефолт, но и оставалась возможность с фронта задать сортировку

2022-11-09 08:24 UTC, greybutton commented on app/javascript/components/AddPopup/index.js
> +import AddPopup from './AddPopup.js';
без этого тоже работать должно

2022-11-09 08:24 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +function EditPopup({ cardId, onClose, onDestroyCard, onLoadCard, onUpdateCard }) {
хорошо, можно не переделывать

2022-11-09 08:24 UTC, greybutton commented on package.json
> +    "ramda": "^0.28.0",
в проекте `qs` пакет используется, но его нет в package.json

2022-11-11 07:21 UTC, abolychev commented on app/controllers/api/v1/tasks_controller.rb
> +    search.sorts = 'id desc'
fixed

2022-11-11 07:33 UTC, abolychev commented on package.json
> +    "ramda": "^0.28.0",
fixed

2022-11-11 09:11 UTC, greybutton approved these changes

2022-11-11 09:22 UTC, merged